### ISSUE TITLE
Missing license

### ISSUE THREAD

**Issue by char0n** [webpack/loader-runner#28]
Hello, is it possible to incorporate the LICENSE file inside the repo and npm package ? Now it's missing. It's implied by MIT license that if licensed under the MIT the source code must be accompanied by full license text. If the license file is not in the repo nor npm package and lot of people cannot use it.

Thank you

We've already provided a PR solving this: https://github.com/webpack/loader-runner/pull/27

@ChALkeR, @TheLarkInn, @sokra  could you help us pls or anybody from your webpack org ?

**Comment by ChALkeR** [comment]
@char0n I have no idea why you tagged me here.

**Comment by char0n** [comment]
@ChALkeR I've seen you in various PRs, thought you are associated with this repo. Sorry if I bothered you. I need to resolve this LICENSING issue, because without loader-runner we're not able to use webpack.

**Comment by Bosch-Eli-Black** [comment]
We're also looking for a LICENSE file.

**Comment by char0n** [comment]
@Bosch-Eli-Black can you pls issue a PR exactly the same as https://github.com/webpack/loader-runner/pull/27 ? The thing there is that we cannot sign CLA and proceed further with PR.

So pls copy our PR, sign the CLA (if you can) and @sokra will have no problem merging it, as suggested by approval on our PR. It is a big issue for us also, the code in this repo is at this moment proprietary and we cannot use it.

**Comment by char0n** [comment]
@Bosch-Eli-Black damn, so you're in the same hole as us...

**Comment by Bosch-Eli-Black** [comment]
Thanks, @opichals! :)
